version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fooddb
      - POSTGRES_USER=fooduser
      - POSTGRES_PASSWORD=foodpass
    ports:
      - "5432:5432"

  app:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py populate_db &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=fooddb
      - POSTGRES_USER=fooduser
      - POSTGRES_PASSWORD=foodpass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
